//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace плеер.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int stream {
            get {
                return ((int)(this["stream"]));
            }
            set {
                this["stream"] = value;
            }
        }

    
        public int EchoLevel { get; internal set; }
        public int EQ42Hz { get; internal set; }
        public int EQ72Hz { get; internal set; }
        public int EQ161Hz { get; internal set; }
        public int EQ299Hz { get; internal set; }
        public int EQ637Hz { get; internal set; }
        public int EQ1000Hz { get; internal set; }
        public int EQ2000Hz { get; internal set; }
        public int EQ4000Hz { get; internal set; }
        public int EQ9000Hz { get; internal set; }
        public int TrackBar1Value { get; internal set; }
        public int TrackBar2Value { get; internal set; }
        public int TrackBar3Value { get; internal set; }
        public int TrackBar4Value { get; internal set; }
        public int TrackBar5Value { get; internal set; }
        public int TrackBar6Value { get; internal set; }
        public int TrackBar7Value { get; internal set; }
        public int TrackBar8Value { get; internal set; }
        public int TrackBar9Value { get; internal set; }
        public int TrackBar10Value { get; internal set; }
    }
}
